### ISSUE TITLE
一类动词应该是五段动词，二类动词是一段动词，这边完全错了

### ISSUE THREAD

**Issue by kejinlu** [einverne/japanese-learning-notes#3]
https://github.com/einverne/japanese-learning-notes/blob/e6bef89f7da6b4fbb872f7e0319da892ae87d2d2/docs/post/verb-difference.md?plain=1#L13

**Comment by einverne** [comment]
谢谢反馈，现在就更改一下。因为我学的教材里面都是用 一类，二类，三类来学习的，这里可能我写错了。
